name: bacloud_sdk
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0-266.8.beta <3.0.0'

dependencies:
  pointycastle: ^3.6.0
  convert: ^3.0.2
  cryptography: ^2.0.5
  protobuf: ^2.0.1
  protoc_plugin: ^20.0.0
  tuple: ^2.0.0
  flutter_rust_bridge: ^1.34.2
  fixnum: ^1.0.1
  event_bus: ^2.0.0
  buffer: ^1.1.1
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
